<?php

/**
 * Implementation of hook_menu()
 */
function survey_menu() {
    $items ['survey/message'] = array (
			'title' => '',
			'description' => '',
			'page callback' => 'survey_show_message',
			'access callback' => 'user_is_logged_in',
			'type' => MENU_NORMAL_ITEM,
	);
    return $items;
}

function survey_cowpro_customer_profile_survey_create($values) {
	$values += array (
                        'type' => '风险承受能力问卷用户调查结果',
			'score' => 0,
                        'level' => 1,
	);
	return $values;
}
function survey_cowpro_customer_profile_survey_save($profile) {
	$data = array ();
        $data ['type'] = $profile->type;
	$data ['score'] = $profile->score;
        $data ['level'] = $profile->level;
	$profile->data = $data;
	$profile->search_field = $profile->score."|".$profile->level;
	return $profile;
}
function survey_cowpro_customer_profile_survey_load($profile) {
        $profile->type = $profile->data ['type'];
	$profile->score = $profile->data ['score'];
        $profile->level = $profile->data ['level'];
	return $profile;
}

/**
 * Implements hook_cowpro_customer_profile_type_info().
 */
function survey_cowpro_customer_profile_type_info() {
	$profile_types = array ();
        $level_array = array(
                        1 => "保守型投资者",
                        2 => "稳健型投资者",
                        3 => "积极型投资者",
                        4 => "激进型投资者",
            
                        );
        global $user;
        $description = "风险承受能力问卷";
        $survey_profile = cowpro_customer_profile_load_one_row_with_conditions($user->uid,"survey");
        if( $survey_profile != NULL && $survey_profile->verified ) {
            $description = $level_array[$survey_profile->level];
        }
	$profile_types ['survey'] = array (
			'type' => 'survey',
			'name' => '风险评测',
			'description' => $description,
			'help' => '',
			'weight' => 100
	);

	return $profile_types;
}

function survey_user_view_detail($profile){
    
	$goto_url = $GLOBALS['base_url'] . "/survey";
	if ($profile) {
		if (! $profile->verified) {
			$verified = FALSE;
			$markup = '去评测';
			$message = "您还未进行风险评测<a href='" . $goto_url . "' class='gotourl'>去评测</a>";
		} else {
                    $verified = TRUE;
                    $markup = '已评测';
                    $message = "";
                }
        }else {
		$verified = FALSE;
		$markup = '去评测';
		$message = "您还未进行风险评测<a href='" . $goto_url . "' class='gotourl'>去评测</a>";
	}
        $result ['verified'] = $verified;
	$result ['markup'] = $markup;
	$result ['message'] = $message;
        return $result;
                

}

/**
 * Implements hook_form_alter().
 */
function survey_form_alter(&$form, &$form_state, $form_id) {

  if (isset($form['#node']->type) && $form_id == $form['#node']->type . '_node_form' && variable_get('webform_node_' . $form['#node']->type, FALSE)) {
      if( !_survey_ismobile_device() ) {
        $form['#node']->webform['redirect_url'] = '';
      }
  }
}

/**
 * Implements hook_node_insert().
 */
function survey_node_insert($node){
    if ( isset($node->webform) ) {
        $node->webform['submit_notice'] = 0;
    }
}

/**
 * Implements hook_node_load().
 */
function survey_node_load($nodes, $types) {
    $webform_types = webform_node_types();
  if (count(array_intersect($types, $webform_types)) == 0) {
    return;
  }

    foreach( $nodes as $nid => $webform ){
        $webform->webform['submit_notice'] = 0;
        $webform->webform['preview_message'] = "";
   
        if( isset($webform->webform['components']) ) {
            foreach( $webform->webform['components'] as $key=>$value ){
                if( $value["type"] == "pagebreak" && !_survey_ismobile_device() ) {
                    unset($nodes[$nid]->webform['components'][$key]);
                }
            }
        }
    } 
}


// 判断是否是移动端
function _survey_ismobile_device() {
	$browser = browscap_get_browser ();
	if ($browser ['ismobiledevice'] == "true") {
		return true;
	} else {
		return false;
	}
}

function survey_webform_submission_presave($node, &$submission){
    $components = $node->webform['components'];
    $components_result = $submission->data;
    $components_result_parser = array();

    foreach( $components as $key=>$value ){
        if( isset($components_result[$key]) ) {
            $components_result_parser[$value['form_key']] = $components_result[$key][0];
        }
    }

    $result = array();
    $total_score = 0;
    $fractional_structure = array(
        "subject1" => array("a"=>3,"b"=>2,"c"=>1,"d"=>1,"e"=>0),
        "subject2" => array("a"=>1,"b"=>3,"c"=>4,"d"=>5,"e"=>6),
        "subject3" => array("a"=>3,"b"=>2,"c"=>1,"d"=>0),
        "subject4" => array("a"=>0,"b"=>1,"c"=>2,"d"=>3),
        "subject5" => array("a"=>5,"b"=>5,"c"=>5,"d"=>0),
        "subject6" => array("a"=>1,"b"=>2,"c"=>3,"d"=>5),
        "subject7" => array("a"=>1,"b"=>2,"c"=>3,"d"=>4),
        "subject8" => array("a"=>1,"b"=>3,"c"=>4,"d"=>6),
        "subject9" => array("a"=>0,"b"=>1,"c"=>2,"d"=>4,"e"=>6),
        "subject10" => array("a"=>1,"b"=>2,"c"=>3,"d"=>4,"e"=>0),
        "subject11" => array("a"=>1,"b"=>3,"c"=>5),
        "subject12" => array("a"=>2,"b"=>4,"c"=>5,"d"=>6,"e"=>6),
        "subject13" => array("a"=>0,"b"=>1,"c"=>3,"d"=>5,"e"=>6),
        "subject14" => array("a"=>0,"b"=>2,"c"=>3,"d"=>4),
        "subject15" => array("a"=>0,"b"=>2,"c"=>4,"d"=>6),
        "subject16" => array("a"=>7,"b"=>5,"c"=>4,"d"=>3,"e"=>1),
        "subject17" => array("a"=>5,"b"=>7,"c"=>3,"d"=>2,"e"=>0),
        "subject18" => array("a"=>5,"b"=>3,"c"=>1),
        "subject19" => array("a"=>1,"b"=>2,"c"=>4,"d"=>5),
        "subject20" => array("a"=>4,"b"=>3,"c"=>2,"d"=>1,"e"=>0),
    );
    foreach( $components_result_parser as $key=>$value ){
        if( isset($fractional_structure[$key]) ) {
            $total_score += $fractional_structure[$key][$value];
        }
    }

    global $user;
    
   $survey_profile = cowpro_customer_profile_load_one_row_with_conditions($user->uid,"survey");
   if ($survey_profile == NULL) {
            $survey_profile = cowpro_customer_profile_new ( 'survey', $user->uid );
    }
    $level = array(
                1 => array("min"=>0,"max"=>25),
                2 => array("min"=>26,"max"=>50),
                3 => array("min"=>51,"max"=>75),
                4 => array("min"=>76,"max"=>100),
        
            );
    $level_result = 1;
    foreach( $level as $key=>$value ){
        if( $total_score >= $value['min'] &&  $total_score <= $value['max']) {
            $level_result = $key;
            break;
        }
    }
    
   $survey_profile->score = $total_score;
   $survey_profile->level = $level_result;
   $survey_profile->verified = true;
   cowpro_customer_profile_save($survey_profile);
   
   if( !_survey_ismobile_device() ) {
          $level_array = array(
            1 => array("title"=>"保守型投资者","des"=>"根据评测结果：您的风险承担能力水平比较低， 您关注资产的安全性远超于资产的收益性， 所以低风险、高流动性的投资品种比较适合您。"),
            2 => array("title"=>"稳健型投资者","des"=>"根据评测结果：您有比较有限的风险承受能力，对投资收益比较敏感，期望通过短期、持续、渐进的投资获得高于定期存款的回报。"),
            3 => array("title"=>"积极型投资者","des"=>"根据评测结果：您有中高的风险承受能力，愿意承担可预见的投资风险去获取更多的收益，以一定的可预见风险换取超额收益。"),
            4 => array("title"=>"激进型投资者","des"=>"根据评测结果：您有较高的风险承受能力，是富有冒险精神的积极型选手。在投资收益波动的情况下， 仍然保持积极进取的投资理念。"),

            );
    drupal_set_message('<div class="survey_message">'.$level_array[$level_result]["title"].'</div><div>'.$level_array[$level_result]["des"].'</div>');
    drupal_goto("/registration_wizard");
   }
}

function survey_show_message(){
    global $user;
     $survey_profile = cowpro_customer_profile_load_one_row_with_conditions($user->uid,"survey");
     $level_array = array(
                        1 => array("title"=>"保守型投资者","des"=>"根据评测结果：您的风险承担能力水平比较低， 您关注资产的安全性远超于资产的收益性， 所以低风险、高流动性的投资品种比较适合您。"),
                        2 => array("title"=>"稳健型投资者","des"=>"根据评测结果：您有比较有限的风险承受能力，对投资收益比较敏感，期望通过短期、持续、渐进的投资获得高于定期存款的回报。"),
                        3 => array("title"=>"积极型投资者","des"=>"根据评测结果：您有中高的风险承受能力，愿意承担可预见的投资风险去获取更多的收益，以一定的可预见风险换取超额收益。"),
                        4 => array("title"=>"激进型投资者","des"=>"根据评测结果：您有较高的风险承受能力，是富有冒险精神的积极型选手。在投资收益波动的情况下， 仍然保持积极进取的投资理念。"),
            
                        );
     $html = theme ( 'survey_message', array (
			'title' => $level_array[$survey_profile->level]["title"],
                        'des' => $level_array[$survey_profile->level]["des"],
     ) );
    return $html;
}

/**
 * Implements hook_theme().
 */
function survey_theme() {
	return array (
			'survey_message' => array (
					'variables' => array (
                                            'title' => null,
                                            'des' => null,
					),
					'template' => 'survey-message'
			),
	);
}